SELECT A.ID AS INCIDENT_NUMBER,A.IMPACT_START_UTC AS START_TIME, A.TITLE AS BRIEF_DESCRIPTION, A.STATUS, NEXT_STEPS AS SUMMARY, B.REGION AS LOCATION 
FROM ITSM_OWNER.SRC_GCC_EVENTS A LEFT JOIN ITSM_OWNER.SRC_GCC_EVENT_LOCATIONS B ON (A.ID = B.EVENT_ID)
WHERE SEVERITY = 'Managed Problem' and STATUS = 'Active' ORDER BY SUBMITTED_ON_UTC DESC
